### ISSUE TITLE
Create new papriika-nodemailer repository

### ISSUE THREAD

**Issue by guylepage3** [papriika/papriika#1]
**Description**
Create new `papriika-nodemailer` repository.

**Tasks**
- [x] Create repository with README and description.
- [x] Create issue templates.
- [x] Import labels via [guylepage3/import-github-labels.md](https://gist.github.com/guylepage3/51d8264e47b3eb013e905b1c088ffa8e).
- [x] Add repository to Slack.

**Comment by guylepage3** [comment]
Done

**Comment by guylepage3** [comment]
https://github.com/papriika/papriika-nodemailer
